import type { ControlRoomSnapshot, Milestone } from "@/lib/domain/types";

const UPDATED_AT = "2026-08-12T00:40:00-06:00";

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: "M0",
    name: "Readiness",
    owner: "Teckel Product & Engineering",
    status: "EVIDENCE_READY",
    gate: "EXTEND",
    dueDate: "2026-08-12",
    acceptance: "Paquete documental auditado; PASS depende de Anexo A, contrato ejecutado, certificado y evidencia de inicio.",
    evidence: [
      "docs/01-requirements-traceability.csv",
      "docs/02-raci.md",
      "docs/03-risk-register.md",
      "docs/04-bill-of-materials.md",
      "docs/09-decision-register.md",
      "docs/evidence/M0-evidence-report.md",
    ],
    blocker: "Anexo A, contrato ejecutado, certificado y constancia de inicio no archivados.",
    nextAction: "Ingerir, conciliar y hashear los cuatro insumos cuando existan.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M1",
    name: "Control Tower y golden path local",
    owner: "Teckel Product & Engineering",
    status: "EVIDENCE_READY",
    gate: "PASS",
    dueDate: "2026-08-12",
    acceptance: "Transacción sintética E2E trazable, idempotencia y kill switch probados.",
    evidence: [
      "supabase/tests/001_core_gate.sql",
      "tests/e2e/surfaces.spec.ts",
      "docs/evidence/M1-gate-report.md",
    ],
    blocker: null,
    nextAction: "Conservar baseline y revalidar el golden path con cada cambio material.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M2",
    name: "Datos, seguridad y recuperación",
    owner: "Teckel Product & Engineering",
    status: "EVIDENCE_READY",
    gate: "EXTEND",
    dueDate: "2026-08-25",
    acceptance: "Restore, RLS, MFA, supresión y threat model sin P0 abiertos.",
    evidence: [
      "supabase/migrations/202608110002_secure_document_storage.sql",
      "evidence/m2-restore/summary.json",
      "docs/06-threat-model.md",
      "docs/12-m2-architecture.md",
    ],
    blocker: "Proveedor, legal, credenciales rotadas, antivirus y recuperación real requieren gates externos.",
    nextAction: "Ejecutar canary aislado de Auth, Storage y restore cuando exista infraestructura autorizada.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M3",
    name: "Captación y precotización",
    owner: "Teckel Product & Engineering",
    status: "EVIDENCE_READY",
    gate: "EXTEND",
    dueDate: "2026-09-01",
    acceptance: "Modelo aprobado, PDF, mobile, desktop y captura E2E.",
    evidence: [
      "docs/evidence/M3-gate-report.md",
      "docs/evidence/M3-prequote-model-verification.json",
      "supabase/tests/004_public_prequote_capture_gate.sql",
      "supabase/tests/005_conversion_analytics_gate.sql",
    ],
    blocker: "Modelo requiere validación de Paco, aviso requiere aprobación y recibos requieren antivirus real.",
    nextAction: "Mantener release público cerrado hasta resolver los tres gates externos.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M4",
    name: "Portal y operación",
    owner: "Teckel Product & Engineering",
    status: "EVIDENCE_READY",
    gate: "EXTEND",
    dueDate: "2026-09-08",
    acceptance: "ENNCO opera leads, respuestas, pipeline, reportes y exportación.",
    evidence: [
      "supabase/tests/006_gmail_operations_gate.sql",
      "src/lib/operations/portal.ts",
      "tests/e2e/surfaces.spec.ts",
    ],
    blocker: "Gmail, Pub/Sub, KMS y Supabase real no están provisionados ni autorizados.",
    nextAction: "Validar el mismo flujo en staging aislado y ejecutar UAT con operador ENNCO.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M5",
    name: "Shadow canary",
    owner: "QA independiente",
    status: "EVIDENCE_READY",
    gate: "EXTEND",
    dueDate: "2026-09-15",
    acceptance: "14 días sin P0/P1 y decisión PASS.",
    evidence: [
      "docs/evidence/M5-accelerated-canary.json",
      "supabase/tests/007_shadow_canary_gate.sql",
      "data/campaigns/campaign-manifest-draft-v1.json",
      "src/lib/assistant/policy.test.ts",
    ],
    blocker: "El harness local pasa, pero faltan staging administrado y 14 días reales consecutivos.",
    nextAction: "Provisionar staging autorizado y ejecutar el run real sin tráfico externo.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M6",
    name: "Primer correo",
    owner: "Teckel Revenue Operations",
    status: "BLOCKED",
    gate: "EXTEND",
    dueDate: "2026-09-16",
    acceptance: "Cinco correos aprobados, monitoreados y revisados durante 24 horas.",
    evidence: [
      "docs/evidence/M6-first-send-readiness.json",
      "supabase/tests/008_first_send_release_gate.sql",
      "data/release/domain-readiness-ledger-v1.json",
      "data/release/first-send-readiness-v1.json",
    ],
    blocker: "Anexo A, contrato ejecutado, legal, dominios, DNS, 35 días, canary live, cinco cuentas y aprobación explícita.",
    nextAction: "Resolver evidencia externa. Mantener HOLD y cero destinatarios hasta que los 30 gates live estén en PASS.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M7",
    name: "Escalamiento controlado",
    owner: "Teckel Revenue Operations",
    status: "BLOCKED",
    gate: "EXTEND",
    dueDate: "2026-10-06",
    acceptance: "Primeras 100 entregas válidas, T0 y lotes progresivos con salud estable.",
    evidence: [
      "supabase/tests/009_controlled_scaling_gate.sql",
      "src/lib/scaling/health.test.ts",
      "docs/17-m7-controlled-scaling-architecture.md",
      "docs/evidence/M7-gate-report.md",
    ],
    blocker: "M6 sigue en EXTEND. Hay 0 de 100 entregas válidas y T0 no existe.",
    nextAction: "Conservar HOLD. Liberar cada ola sólo después de salud live PASS y aprobación exacta.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M8",
    name: "Primer mes completo",
    owner: "Teckel Revenue Operations",
    status: "BLOCKED",
    gate: "EXTEND",
    dueDate: "2026-10-31",
    acceptance: "Reporte contractual con denominadores, evidencia y meta de diez leads estrictos.",
    evidence: [
      "supabase/tests/010_contractual_monthly_reporting_gate.sql",
      "src/lib/reporting/monthly.test.ts",
      "docs/18-m8-contractual-reporting-architecture.md",
      "docs/evidence/M8-gate-report.md",
    ],
    blocker: "M6 y M7 siguen en EXTEND. No existe un mes calendario completo ni reporte contractual live.",
    nextAction: "Registrar verdad diaria live y emitir sólo con mes completo, calendario aprobado y evidencia estricta.",
    updatedAt: UPDATED_AT,
  },
  {
    id: "M9",
    name: "Hardening y entrega",
    owner: "Teckel Product & Engineering",
    status: "EVIDENCE_READY",
    gate: "EXTEND",
    dueDate: "2026-11-03",
    acceptance: "Restore, auditoría, UAT, capacitación, accesos, exportaciones y aceptación final.",
    evidence: [
      "supabase/tests/011_handoff_acceptance_gate.sql",
      "src/lib/handoff/readiness.test.ts",
      "docs/19-m9-handoff-architecture.md",
      "docs/evidence/M9-gate-report.md",
    ],
    blocker: "M0 y M2 a M8 conservan gates live abiertos. Faltan UAT, capacitación, transferencia, restore live y aceptación ENNCO.",
    nextAction: "Conservar EVIDENCE_READY local. Ejecutar los diez checks live y solicitar aceptación sólo cuando no exista P0/P1.",
    updatedAt: UPDATED_AT,
  },
];

export function getSyntheticControlRoomSnapshot(): ControlRoomSnapshot {
  return {
    evidenceClass: "synthetic_demo",
    generatedAt: new Date().toISOString(),
    system: {
      environment: "local",
      killSwitch: true,
      externalSendAllowed: false,
      openP0: 11,
      openP1: 7,
    },
    commercial: {
      researchedCompanies: 0,
      verifiedContacts: 0,
      deliveredMessages: 0,
      substantiveReplies: 0,
      contractualLeads: 0,
      qualifiedOpportunities: 0,
      wonProjects: 0,
      firstPaymentsMxn: 0,
    },
    milestones: INITIAL_MILESTONES,
  };
}
